### PR TITLE
fix: example clients_everything_stdio

### LINKED ISSUE #769: Example *clients_everything_stdio* fails when requesting the first resource
**Describe the bug**
Example *clients_everything_stdio* throws the following error:
Error: Mcp error: -32602: MCP error -32602: Resource test://static/resource/3 not found

It looks like the sample mcp server used: "@modelcontextprotocol/server-everything" does not longer have the resource

**To Reproduce**
1.  execute:  cargo run -p mcp-client-examples --example clients_everything_stdio

**Expected behavior**
Example should finish successfully.

### PR DESCRIPTION
**Pull request by adrianromero**
This change fixes #769

## Motivation and Context
Very simple fix that resolves the execution of the example Full-Featured Standard I/O Client (everything_stdio.rs)

## How Has This Been Tested?
Just running the example locally:
Full-Featured Standard I/O Client (everything_stdio.rs)

## Breaking Changes
No

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist
- [X] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [X] My code follows the repository's style guidelines
- [X] New and existing tests pass locally
- [ ] I have added appropriate error handling (Not required)
- [ ] I have added or updated documentation as needed (not required

### CODE REVIEW

**Comment by adrianromero** [comment]
Commit message fixed due to CI failure

File: examples/clients/src/everything_stdio.rs [hunk 1]
```diff
@@ -69,18 +71,18 @@ async fn main() -> Result<()> {
 
     // Get simple prompt
     let prompt = client
-        .get_prompt(GetPromptRequestParams::new("simple_prompt"))
+        .get_prompt(GetPromptRequestParams::new("simple-prompt"))
         .await?;
     tracing::info!("Prompt - simple: {prompt:#?}");
 
     // Get complex prompt (returns text & image)
```
Comment (DaleSeo) [inline examples/clients/src/everything_stdio.rs]:
```suggestion
    // Get prompt with arguments
```

**Review by DaleSeo — APPROVED** [review]
Thanks for fixing this, @adrianromero! Could update the comment to match the new behavior? Other than that, it looks great!
