### PR TITLE
fix(rmcp): surface JSON-RPC error bodies on HTTP 4xx responses

### LINKED ISSUE #724: reqwest streamable HTTP client drops JSON-RPC error bodies on HTTP 4xx into TransportSend
**Describe the bug**
A `POST` over Streamable HTTP that returns `HTTP 4xx` with `Content-Type: application/json` and a valid JSON-RPC error body is currently surfaced by the reqwest client as a transport error (`UnexpectedServerResponse` -> `ServiceError::TransportSend`) instead of a parsed JSON-RPC error (`ServiceError::McpError`).

This was reported in PR comment thread:
https://github.com/modelcontextprotocol/rust-sdk/pull/709#issuecomment-3994373746

**To Reproduce**
1. Use the current `main` behavior in `crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs` where non-2xx is handled before JSON parsing.
2. Send a request to a server that responds with:
   - status: `400 Bad Request`
   - header: `Content-Type: application/json`
   - body: `{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"Unknown prompt: example_prompt"}}`
3. Observe the response is returned as transport error instead of JSON-RPC error object.

Regression test I added for this behavior:
- `crates/rmcp/tests/test_streamable_http_http_error_jsonrpc.rs`

Command used:
```bash
cargo test -p rmcp --test test_streamable_http_http_error_jsonrpc --features "client server transport-streamable-http-client-reqwest transport-streamable-http-server"
```

**Expected behavior**
If response body is valid JSON-RPC and `Content-Type` is `application/json`, it should be parsed and surfaced as JSON-RPC message (so request callers receive `ServiceError::McpError` for error responses), even when HTTP status is 4xx.

This appears consistent with Streamable HTTP spec language that for non-accepted inputs, server may return HTTP error status and response body may be JSON-RPC error response:
- https://modelcontextprotocol.io/specification/2025-11-25/basic/transports#sending-messages-to-the-server
- https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#sending-messages-to-the-server

**Logs**
Observed error shape from failing regression expectation before fix:
```text
Err(UnexpectedServerResponse("HTTP 400 Bad Request: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32602,\"message\":\"Unknown prompt: example_prompt\"}}"))
```

**Additional context**
- I have a proposed fix on branch `fix-streamable-http-400-jsonrpc-error-mapping` in my fork, but I am opening this issue first per `docs/CONTRIBUTE.MD` (“Discuss first”).
- Branch: https://github.com/adam-r-kowalski/rust-sdk/tree/fix-streamable-http-400-jsonrpc-error-mapping
- Commit: https://github.com/adam-r-kowalski/rust-sdk/commit/360557f
- Compare: https://github.com/adam-r-kowalski/rust-sdk/compare/main...fix-streamable-http-400-jsonrpc-error-mapping
- Proposed behavior keeps existing stale-session status-aware error behavior for non-JSON HTTP errors.

### PR DESCRIPTION
**Pull request by kakarot-dev**
When a server returns a 4xx status with Content-Type: application/json, attempt to deserialize the body as a ServerJsonRpcMessage before falling back to UnexpectedServerResponse. This allows JSON-RPC error payloads carried on HTTP error responses to be surfaced as McpError instead of being lost in a transport-level error string.

Fixes #724

Attempt to deserialize HTTP 4xx response bodies as ServerJsonRpcMessage when Content-Type: application/json, surfacing JSON-RPC errors as McpError instead of discarding them as UnexpectedServerResponse.

## How Has This Been Tested?
Tested locally with a mock axum server against three scenarios: valid JSON-RPC error body on 400, non-JSON 400, and malformed JSON on 400. All pass.

## Breaking Changes
None.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have added or updated documentation as needed

## Additional context
I created a test file locally, Test file available if needed

### CODE REVIEW

File: crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs [hunk 1]
```diff
@@ -190,21 +190,42 @@ impl StreamableHttpClient for reqwest::Client {
...
         if !status.is_success() {
             let body = response
                 .text()
                 .await
                 .unwrap_or_else(|_| "<failed to read response body>".to_owned());
+            if content_type
+                .as_deref()
+                .is_some_and(|ct| ct.as_bytes().starts_with(JSON_MIME_TYPE.as_bytes()))
+            {
+                match serde_json::from_str::<ServerJsonRpcMessage>(&body) {
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs]: `ServerJsonRpcMessage` can parse any valid JSON-RPC message including `Request`, `Response`, `Notification`, not just `Error`. The deserialization should verify the parsed message is actually a `JsonRpcMessage::Error`.

File: crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs [hunk 2]
```diff
@@ -190,21 +190,42 @@ impl StreamableHttpClient for reqwest::Client {
...
+            .map(|ct| String::from_utf8_lossy(ct.as_bytes()).to_string());
+        let session_id = response
+            .headers()
+            .get(HEADER_SESSION_ID)
+            .and_then(|v| v.to_str().ok())
+            .map(|s| s.to_string());
+        // For non-success responses, attempt to parse JSON-RPC error bodies
+        // before falling back to a transport error. HTTP 4xx responses with
+        // Content-Type: application/json may carry valid JSON-RPC error
+        // payloads that should be surfaced as McpError, not TransportSend.
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs]: The comment says "HTTP 4xx responses" but the guard is `!status.is_success()`, which also covers 1xx, 3xx, and 5xx. This could be clearer and simpler.

```suggestion
        // Non-success responses may carry valid JSON-RPC error payloads that
        // should be surfaced as McpError rather than lost in TransportSend.
```

Comment (kakarot-dev) [reply crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs]: updated the comments, thank you

File: crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs (hunk 1 above)
Comment (kakarot-dev) [reply crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs]: sorry about that, updated it so that it now only matches `JsonRpcMessage::Error`
