### PR TITLE
fix(auth): redact secrets in Debug output for StoredCredentials and StoredAuthorizationState

### LINKED ISSUE #741: bug - [derive(Debug)] cred leak
**Describe the bug**

`StoredCredentials` and `StoredAuthorizationState` in `crates/rmcp/src/transport/auth.rs` both derive `#[derive(Debug)]`. This causes secret fields — OAuth access tokens, refresh tokens, PKCE verifiers, and CSRF tokens — to be printed in plaintext whenever these types are formatted via a `Debug` formatter. There is no compiler warning or type-system protection against this.

**To Reproduce**

1. Add the `auth` feature to your `rmcp` dependency.
2. Run an OAuth flow to populate a `StoredAuthorizationState` or `StoredCredentials`.
3. Format either type using `{:?}` in any log call:
```rust
tracing::error!("auth state: {:?}", stored_state);
```
4. Observe that live PKCE verifiers, CSRF tokens, access tokens, and refresh tokens are emitted in plaintext to log output.

**Expected behavior**

Secret fields should be redacted in `Debug` output:
```
StoredAuthorizationState { pkce_verifier: [REDACTED], csrf_token: [REDACTED], created_at: 1234567890 }
```

**Logs**

Current `{:?}` output for `StoredAuthorizationState`:
```
StoredAuthorizationState { 
    pkce_verifier: "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk", 
    csrf_token: "xK9mP2nQ8rL4vT6wY1uZ3aB5cD7eF0gH",
    created_at: 1741564800
}
```

**Additional context**

Affected types:

`StoredCredentials` (`auth.rs` line 62) — `token_response` contains `access_token` and `refresh_token`:
```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredCredentials {
    pub client_id: String,
    pub token_response: Option<OAuthTokenResponse>,
    pub granted_scopes: Vec<String>,
    pub token_received_at: Option<u64>,
}
```

`StoredAuthorizationState` (`auth.rs` line 122):
```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredAuthorizationState {
    pub pkce_verifier: String,
    pub csrf_token: String,
    pub created_at: u64,
}
```

The MCP spec's own auth guidance explicitly states: "Don't log credentials. Never log Authorization headers, tokens, codes, or secrets." The current type definitions make it easy to violate this by accident — including via `anyhow`/`thiserror` error chains that automatically format `Debug` representations of involved values.

Suggested fix: use the [`[secrecy](https://crates.io/crates/secrecy)`](https://crates.io/crates/secrecy) crate. Wrap secret fields in `SecretString`, whose `Debug` impl prints `[REDACTED]` and requires `.expose_secret()` for access. Its `serde` feature keeps serialisation transparent so `CredentialStore` implementations are unaffected. Note that `OAuthTokenResponse` comes from the `oauth2` crate and cannot be wrapped directly — `Debug` should be implemented manually on `StoredCredentials` to redact that field.

### PR DESCRIPTION
**Pull request by peatey**
## Summary

Fixes #741.

`StoredCredentials` and `StoredAuthorizationState` both derived `#[derive(Debug)]`, causing secret fields — OAuth access/refresh tokens, PKCE verifiers, and CSRF tokens — to be printed in plaintext via any `{:?}` formatter, including log calls and `anyhow`/`thiserror` error chains.

- Removes `Debug` from the derive macros on both types
- Implements `Debug` manually, printing `[REDACTED]` for sensitive fields and leaving non-secret fields (e.g. `client_id`, `created_at`) visible
- Adds regression tests asserting that `{:?}` formatting does not emit plaintext secrets

## Approach notes

`OAuthTokenResponse` comes from the `oauth2` crate and cannot be wrapped directly, so `StoredCredentials` uses a manual `Debug` impl that redacts the entire `token_response` field.

The `secrecy` crate was considered for `StoredAuthorizationState` (wrapping `pkce_verifier`/`csrf_token` in `SecretString`), but `secrecy` intentionally blocks `Serialize` on `Secret<T>` unless the inner type implements the `SerializableSecret` marker trait — which `String` does not, and orphan rules prevent adding it. Since both types are `Serialize + Deserialize` for use with custom `CredentialStore`/`StateStore` backends, field-type changes would break serialization. Manual `Debug` impls are the correct approach for both types.

## Known scope limitation

The fields `pkce_verifier: String` and `csrf_token: String` on `StoredAuthorizationState` remain `pub`. This fix protects against accidentally formatting the *struct* via `{:?}`, but not against a caller extracting the field and formatting it directly (e.g. `format!("{:?}", state.pkce_verifier)`). This is an inherent limitation of the manual-Debug approach vs. type-level wrapping, and is noted here for reviewer awareness.

## Test plan

- [x] `cargo test -p rmcp --features auth` passes
- [x] `cargo clippy -p rmcp --features auth` clean (pre-existing unused import warning unrelated to this change)
- [x] `test_stored_authorization_state_debug_redacts_secrets` — asserts `{:?}` output does not contain raw verifier/csrf values and does contain `[REDACTED]`
- [x] `test_stored_credentials_debug_redacts_token_response` — asserts `{:?}` output does not contain raw access token and does contain `[REDACTED]`

### CODE REVIEW

File: crates/rmcp/src/transport/auth.rs [hunk 1]
```diff
@@ -69,6 +69,17 @@ pub struct StoredCredentials {
...
 }
 
+impl std::fmt::Debug for StoredCredentials {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        f.debug_struct("StoredCredentials")
+            .field("client_id", &self.client_id)
+            .field("token_response", &self.token_response.as_ref().map(|_| "[REDACTED]"))
+            .field("granted_scopes", &self.granted_scopes)
+            .field("token_received_at", &self.token_received_at)
+            .finish()
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/auth.rs:82]: This will add `..` to the output, indicating that there are additional fields not shown here. It makes it clear to future contributors that they need to explicitly opt new fields into the `Debug` impl.

```suggestion
            .finish_non_exhaustive()()
```

File: crates/rmcp/src/transport/auth.rs [hunk 2]
```diff
@@ -119,13 +130,23 @@ impl CredentialStore for InMemoryCredentialStore {
...
     pub created_at: u64,
 }
 
+impl std::fmt::Debug for StoredAuthorizationState {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        f.debug_struct("StoredAuthorizationState")
+            .field("pkce_verifier", &"[REDACTED]")
+            .field("csrf_token", &"[REDACTED]")
+            .field("created_at", &self.created_at)
+            .finish()
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/auth.rs:149]: Same feedback here.

File: crates/rmcp/src/transport/auth.rs [hunk 3]
```diff
@@ -2776,6 +2797,41 @@ mod tests {
...
+        let debug_output = format!("{:?}", state);
+
+        assert!(!debug_output.contains("super-secret-verifier"));
+        assert!(!debug_output.contains("super-secret-csrf"));
+        assert!(debug_output.contains("[REDACTED]"));
+    }
+
+    #[test]
+    fn test_stored_credentials_debug_redacts_token_response() {
+        use super::{OAuthTokenResponse, StoredCredentials, VendorExtraTokenFields};
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/auth.rs]: It's already imported at the top.

```suggestion
        use super::{OAuthTokenResponse, StoredCredentials};
```

File: crates/rmcp/src/transport/auth.rs [hunk 4]
```diff
@@ -2776,6 +2797,41 @@ mod tests {
...
+    #[test]
+    fn test_stored_authorization_state_debug_redacts_secrets() {
+        let pkce = PkceCodeVerifier::new("super-secret-verifier".to_string());
+        let csrf = CsrfToken::new("super-secret-csrf".to_string());
+        let state = StoredAuthorizationState::new(&pkce, &csrf);
+        let debug_output = format!("{:?}", state);
+
+        assert!(!debug_output.contains("super-secret-verifier"));
+        assert!(!debug_output.contains("super-secret-csrf"));
+        assert!(debug_output.contains("[REDACTED]"));
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/auth.rs:2812]:
```suggestion
        assert!(debug_output.contains("[REDACTED]"));
        assert!(debug_output.contains("created_at"));
```

**Comment by peatey** [comment]
ok fmt now run (its in the workflow so not sure what happened there, sorry) - issues addressed.

File: crates/rmcp/src/transport/auth.rs [hunk 5]
```diff
@@ -2776,6 +2800,43 @@ mod tests {
...
+        assert!(debug_output.contains("created_at"));
+        assert!(debug_output.contains("created_at"));
+    }
+
+    #[test]
+    fn test_stored_credentials_debug_redacts_token_response() {
+        use super::{OAuthTokenResponse, StoredCredentials};
+        use oauth2::{AccessToken, basic::BasicTokenType};
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/auth.rs]: Formatting issue again 😅
https://github.com/modelcontextprotocol/rust-sdk/actions/runs/23006111727/job/66876361029?pr=744

```suggestion
        use oauth2::{AccessToken, basic::BasicTokenType};
        
        use super::{OAuthTokenResponse, StoredCredentials};
```

File: crates/rmcp/src/transport/auth.rs [hunk 6]
```diff
@@ -2776,6 +2800,44 @@ mod tests {
...
+        assert!(debug_output.contains("[REDACTED]"));
+        assert!(debug_output.contains("created_at"));
+        assert!(debug_output.contains("created_at"));
+    }
+
+    #[test]
+    fn test_stored_credentials_debug_redacts_token_response() {
+        use oauth2::{AccessToken, basic::BasicTokenType};
+        
+        use super::{OAuthTokenResponse, StoredCredentials};
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/auth.rs:2821]:
```suggestion
        use oauth2::{AccessToken, basic::BasicTokenType};
        use super::{OAuthTokenResponse, StoredCredentials};
```

File: crates/rmcp/src/transport/auth.rs [hunk 7]
```diff
@@ -2776,6 +2800,43 @@ mod tests {
...
+        assert!(!debug_output.contains("super-secret-csrf"));
+        assert!(debug_output.contains("[REDACTED]"));
+        assert!(debug_output.contains("created_at"));
+        assert!(debug_output.contains("created_at"));
+    }
+
+    #[test]
+    fn test_stored_credentials_debug_redacts_token_response() {
+        use oauth2::{AccessToken, basic::BasicTokenType};
+        use super::{OAuthTokenResponse, StoredCredentials};
```
Comment (DaleSeo) [inline crates/rmcp/src/transport/auth.rs:2821]:
```suggestion
        use oauth2::{AccessToken, basic::BasicTokenType};
        
        use super::{OAuthTokenResponse, StoredCredentials};
```

File: crates/rmcp/src/transport/auth.rs (hunk 6 above)
Comment (DaleSeo) [inline crates/rmcp/src/transport/auth.rs:2821]:
```suggestion
        use oauth2::{AccessToken, basic::BasicTokenType};

        use super::{OAuthTokenResponse, StoredCredentials};
```

**Comment by DaleSeo** [comment]
Hey @jamadeo, could you help approve/merge this PR? I've fixed the formatting issue on the web, but now it seems like someone else needs to approve it since I've added commits technically. 😂
