### PR TITLE
fix(tasks): #626 model task capabilities correctly

### LINKED ISSUE #626: in 0.13.0, TasksCapability structure has incorrect types
Comparing

https://github.com/modelcontextprotocol/rust-sdk/blob/e623f2acabd53e51a978d160f955c315bc16c220/crates/rmcp/src/model/capabilities.rs#L47

with

https://github.com/modelcontextprotocol/modelcontextprotocol/blob/main/schema/2025-11-25/schema.ts#L433

the fields should be maps, not booleans

### PR DESCRIPTION
**Pull request by alexhancock**
Fixes #626 

Capabilities for tasks take the following form.

**Client**
```
{
  "capabilities": {
    "tasks": {
      "list": {},
      "cancel": {},
      "requests": {
        "sampling": {
          "createMessage": {}
        },
        "elicitation": {
          "create": {}
        }
      }
    }
  }
}
```

**Server**
```
{
  "capabilities": {
    "tasks": {
      "list": {},
      "cancel": {},
      "requests": {
        "tools": {
          "call": {}
        }
      }
    }
  }
}
```

We were previously using booleans to model these instead of objects, causing errors during initialization between servers and clients that expressed these capabilities

### CODE REVIEW

File: crates/rmcp/src/model/capabilities.rs [hunk 1]
```diff
@@ -368,4 +465,61 @@ mod test {
...
+        // Verify structure
+        assert!(tasks.supports_list());
+        assert!(tasks.supports_cancel());
+        assert!(tasks.supports_sampling_create_message());
+        assert!(tasks.supports_elicitation_create());
+        assert!(!tasks.supports_tools_call());
+        
+        // Verify serialization matches expected format
+        let json = serde_json::to_value(&tasks).unwrap();
+        assert_eq!(json["list"], serde_json::json!({}));
```
Comment (jamadeo) [inline crates/rmcp/src/model/capabilities.rs:502]: are these really testing all that much?

Comment (alexhancock) [reply crates/rmcp/src/model/capabilities.rs:502]: not terribly. the serialization one has value but these I agree don't add much. merging for not to not wait for another CI cycle but I will remove them on a future change.
